
- id: "test_bdser_er2_i1_sr"
  desc: "BDSE agent robust, antisym, servo robust L1"
  code:
  - boot_agents_bdse.BDSEAgentRobust
  - estimator: 
    - bdse.BDSEEstimatorRobust
    - rcond: 0.0001
      antisym_T: true    
      antisym_M: false
    importance: 
    - boot_agents.Importance
    - max_y_dot: 0.1
      max_gy: 1000 # this does not penalizes gradients
      min_y: 0
      max_y: 1
    servo: 
    - boot_agents_bdse.BDSEServoRobust # XXX
    - gain: 0.1


- id: test_bdsesagent2
  desc: A BDS agent that decouples the computation of derivative
  code:
  - boot_agents_bdse.BDSEAgent2
  - estimator: 
    - bdse.BDSEEstimator
    - rcond: 0.0001
      antisym_T: true    
      antisym_M: false
    servo: 
    - boot_agents_bdse.BDSEServo # XXX
    - gain: 0.1

# - id: test_bdseagent2_complete
#   desc: ...
#   code:
#   - bootstrapping_olympics.library.agents.NuisanceAgent
#   - agent: test_bdsesagent2
#     nuisances: 
#     - dderivative

