# TODO: other parameters
# antisym_T=False, antisym_M=False,
# use_P_scaling=False, invalid_P_threshold=None)

- id: b_rc0
  desc: "The simplest estimator"
  code:
  - bdse.BDSEEstimator
  - rcond: 0

- id: b_rc05
  desc: "The simplest estimator, positive rcond"
  code:
  - bdse.BDSEEstimator
  - rcond: 0.00001

- id: r_rc0
  desc: "Robustified estimator"
  code:
  - bdse.BDSEEstimatorRobust
  - rcond: 0

- id: r_rc05
  desc: "Robustified estimator"
  code:
  - bdse.BDSEEstimatorRobust
  - rcond: 0.00001

