 

  
- id: test_cond30
  desc: "Estimates the conditional distribution"
  code:
  - boot_agents.EstConditionalDistribution
  - index: 0


- id: test_remove_dead
  desc: Remove dead pixels
  code:
  - boot_agents.RemoveDead
  - perc: 50
    ratio: 0.2


- id: test_multi1
  desc: An example of a multi-level agent.
  code:
  - bootstrapping_olympics.library.agents.MultiLevelAgent
  - agents: 
    - test_remove_dead
    - test_obs_normalize_max
    - test_eststats_t3


- id: test_bgdsagent_C1
  desc: "Dev. version"
  code:
  - boot_agents_bgds.BGDSAgent
  - {}
  

- id: deriv_agent_dummy
  desc: "Dummy version of DerivAgent"
  code:
  - boot_agents.DerivAgentDummy
  - {}

  
- id: deriv_agent_robust_dummy
  desc: "Dummy version of DerivAgentRobust"
  code:
  - boot_agents.DerivAgentRobustDummy
  - {}

  

