- id: test_random_10x10_2
  desc: Random robot (2D observations)
  code:
  - bootstrapping_olympics.library.robots.RandomRobot
  - boot_spec:
      observations:
        shape: [10,10]
        format: C
        range: [0,1]
      commands:
        shape: [2]
        format: C
        range: [-1,+1]
        default: [0,0]

- id: test_random_10_2
  desc: Random robot (1D observations)
  code:
  - bootstrapping_olympics.library.robots.RandomRobot
  - boot_spec:
      observations:
        shape: [10]
        format: C
        range: [0,1]
      commands:
        shape: [2]
        format: C
        range: [-1,+1]
        default: [0,0]
